# 应用服务 WEB 访问端口
server:
    port: 8090

# 应用名称
spring:
    profiles:
        active: prod
    application:
        name: nucoj_spring
    # redis配置
    redis:
        port: 6379
    # rabbit 配置
    rabbitmq:
        port: 5672
        username: guest
        password: guest
        listener:
            simple:
                retry:
                    enabled: true
                    max-attempts: 3 #最大重试次数
                    initial-interval: 3000 #重试间隔时间（单位毫秒）
    data:
        mongodb:
            auto-index-creation: true
    # 邮箱 配置
    mail:
        host: smtp.163.com
        username: a3072844942@163.com
        password: ZEDPDSXFPWMHVCUI
        default-encoding: UTF-8
        port: 587
        properties:
            mail:
                smtp:
                    auth: true
                    socketFactory:
                        class: javax.net.ssl.SSLSocketFactory
    servlet:
      multipart:
          max-file-size: 10MB
          max-request-size: 100MB